// app/components/onboarding/ReviewStep.tsx
import { Badge } from "@/components/ui/badge";
import {
  FileText,
  MapPin,
  Building2,
  Mail,
  Globe,
  CheckCircle2,
} from "lucide-react";
import type { BusinessFormData } from "@/types/onboarding";

interface Props {
  data: BusinessFormData;
}

const Section = ({
  icon: Icon,
  title,
  children,
}: {
  icon: React.ElementType;
  title: string;
  children: React.ReactNode;
}) => (
  <div className="space-y-3">
    <div className="flex items-center gap-2 text-primary">
      <Icon className="w-4 h-4" />
      <h4 className="font-semibold text-sm">{title}</h4>
    </div>
    <div className="pl-6 space-y-2">{children}</div>
  </div>
);

const Field = ({ label, value }: { label: string; value: string }) => (
  <div className="flex justify-between text-sm">
    <span className="text-muted-foreground">{label}</span>
    <span className="font-medium text-right max-w-[60%]">{value || "—"}</span>
  </div>
);

const ReviewStep = ({ data }: Props) => {
  return (
    <div className="space-y-6">
      <div className="p-4 rounded-lg bg-accent/50 border border-accent flex items-start gap-3">
        <CheckCircle2 className="w-5 h-5 text-primary mt-0.5 shrink-0" />
        <div>
          <p className="text-sm font-semibold text-accent-foreground">
            Review Your Information
          </p>
          <p className="text-xs text-muted-foreground mt-1">
            Please confirm all details are correct before submitting your
            business onboarding application.
          </p>
        </div>
      </div>

      <Section icon={Building2} title="Business Information">
        <Field label="Business Name" value={data.businessName} />
        <Field label="Services" value={data.services} />
        <Field label="Email" value={data.email} />
        <Field label="Resident Country" value={data.residentCountry} />
        <Field
          label="Business Type"
          value={data.businessType === "onsite" ? "Onsite" : "Offsite"}
        />
        {data.isRegistered === "yes" && (
          <div className="pt-1">
            <Badge variant="secondary">Registered Business</Badge>
          </div>
        )}
      </Section>

      {data.businessType === "onsite" && (
        <Section icon={MapPin} title="Business Address">
          <Field
            label="Address"
            value={`${data.address.number} ${data.address.street}`}
          />
          <Field label="State" value={data.address.state} />
          <Field label="Country" value={data.address.country} />
          <Field label="Zip Code" value={data.address.zipCode} />
        </Section>
      )}

      {data.isRegistered === "yes" && (
        <Section icon={Globe} title="Registration Details">
          <Field label="Reg. Number" value={data.registration.regNumber} />
          <Field
            label="Country of Incorporation"
            value={data.registration.countryOfIncorporation}
          />
          <Field
            label="CAC"
            value={data.registration.cacDocument?.name || "Not uploaded"}
          />
          <Field
            label="MEMART"
            value={data.registration.memartDocument?.name || "Not uploaded"}
          />
          <Field
            label="Status Report"
            value={data.registration.statusReport?.name || "Not uploaded"}
          />
        </Section>
      )}

      {data.documents.length > 0 && (
        <Section icon={FileText} title={`Documents (${data.documents.length})`}>
          {data.documents.map((doc) => (
            <div key={doc.id} className="flex items-center gap-2 text-sm">
              <FileText className="w-3.5 h-3.5 text-muted-foreground" />
              <span>{doc.name}</span>
            </div>
          ))}
        </Section>
      )}
    </div>
  );
};

export default ReviewStep;

// app/components/onboarding/ReviewStep.vue
<script setup>
import { Badge } from "@/components/ui/badge";
import {
  FileText,
  MapPin,
  Building2,
  Globe,
  CheckCircle2,
} from "lucide-react";

defineProps({
  data: {
    type: Object,
    required: true,
  },
});
</script>

<template>
  <div class="space-y-6">
    <div
      class="p-4 rounded-lg bg-accent/50 border border-accent flex items-start gap-3"
    >
      <CheckCircle2 class="w-5 h-5 text-primary mt-0.5 shrink-0" />
      <div>
        <p class="text-sm font-semibold text-accent-foreground">
          Review Your Information
        </p>
        <p class="text-xs text-muted-foreground mt-1">
          Please confirm all details are correct before submitting your business
          onboarding application.
        </p>
      </div>
    </div>

    <!-- Business Information Section -->
    <div class="space-y-3">
      <div class="flex items-center gap-2 text-primary">
        <Building2 class="w-4 h-4" />
        <h4 class="font-semibold text-sm">Business Information</h4>
      </div>
      <div class="pl-6 space-y-2">
        <div class="flex justify-between text-sm">
          <span class="text-muted-foreground">Business Name</span>
          <span class="font-medium text-right max-w-[60%]">{{
            data.businessName || "—"
          }}</span>
        </div>
        <div class="flex justify-between text-sm">
          <span class="text-muted-foreground">Services</span>
          <span class="font-medium text-right max-w-[60%]">{{
            data.services || "—"
          }}</span>
        </div>
        <div class="flex justify-between text-sm">
          <span class="text-muted-foreground">Email</span>
          <span class="font-medium text-right max-w-[60%]">{{
            data.email || "—"
          }}</span>
        </div>
        <div class="flex justify-between text-sm">
          <span class="text-muted-foreground">Resident Country</span>
          <span class="font-medium text-right max-w-[60%]">{{
            data.residentCountry || "—"
          }}</span>
        </div>
        <div class="flex justify-between text-sm">
          <span class="text-muted-foreground">Business Type</span>
          <span class="font-medium text-right max-w-[60%]">
            {{ data.businessType === "onsite" ? "Onsite" : "Offsite" }}
          </span>
        </div>
        <div v-if="data.isRegistered === 'yes'" class="pt-1">
          <Badge variant="secondary">Registered Business</Badge>
        </div>
      </div>
    </div>

    <!-- Business Address Section -->
    <div v-if="data.businessType === 'onsite'" class="space-y-3">
      <div class="flex items-center gap-2 text-primary">
        <MapPin class="w-4 h-4" />
        <h4 class="font-semibold text-sm">Business Address</h4>
      </div>
      <div class="pl-6 space-y-2">
        <div class="flex justify-between text-sm">
          <span class="text-muted-foreground">Address</span>
          <span class="font-medium text-right max-w-[60%]">
            {{ data.address.number }} {{ data.address.street }}
          </span>
        </div>
        <div class="flex justify-between text-sm">
          <span class="text-muted-foreground">State</span>
          <span class="font-medium text-right max-w-[60%]">{{
            data.address.state || "—"
          }}</span>
        </div>
        <div class="flex justify-between text-sm">
          <span class="text-muted-foreground">Country</span>
          <span class="font-medium text-right max-w-[60%]">{{
            data.address.country || "—"
          }}</span>
        </div>
        <div class="flex justify-between text-sm">
          <span class="text-muted-foreground">Zip Code</span>
          <span class="font-medium text-right max-w-[60%]">{{
            data.address.zipCode || "—"
          }}</span>
        </div>
      </div>
    </div>

    <!-- Registration Details Section -->
    <div v-if="data.isRegistered === 'yes'" class="space-y-3">
      <div class="flex items-center gap-2 text-primary">
        <Globe class="w-4 h-4" />
        <h4 class="font-semibold text-sm">Registration Details</h4>
      </div>
      <div class="pl-6 space-y-2">
        <div class="flex justify-between text-sm">
          <span class="text-muted-foreground">Reg. Number</span>
          <span class="font-medium text-right max-w-[60%]">
            {{ data.registration.regNumber || "—" }}
          </span>
        </div>
        <div class="flex justify-between text-sm">
          <span class="text-muted-foreground">Country of Incorporation</span>
          <span class="font-medium text-right max-w-[60%]">
            {{ data.registration.countryOfIncorporation || "—" }}
          </span>
        </div>
        <div class="flex justify-between text-sm">
          <span class="text-muted-foreground">CAC</span>
          <span class="font-medium text-right max-w-[60%]">
            {{ data.registration.cacDocument?.name || "Not uploaded" }}
          </span>
        </div>
        <div class="flex justify-between text-sm">
          <span class="text-muted-foreground">MEMART</span>
          <span class="font-medium text-right max-w-[60%]">
            {{ data.registration.memartDocument?.name || "Not uploaded" }}
          </span>
        </div>
        <div class="flex justify-between text-sm">
          <span class="text-muted-foreground">Status Report</span>
          <span class="font-medium text-right max-w-[60%]">
            {{ data.registration.statusReport?.name || "Not uploaded" }}
          </span>
        </div>
      </div>
    </div>

    <!-- Documents Section -->
    <div v-if="data.documents.length > 0" class="space-y-3">
      <div class="flex items-center gap-2 text-primary">
        <FileText class="w-4 h-4" />
        <h4 class="font-semibold text-sm">
          Documents ({{ data.documents.length }})
        </h4>
      </div>
      <div class="pl-6 space-y-2">
        <div
          v-for="doc in data.documents"
          :key="doc.id"
          class="flex items-center gap-2 text-sm text-foreground"
        >
          <FileText class="w-3.5 h-3.5 text-muted-foreground" />
          <span>{{ doc.name }}</span>
        </div>
      </div>
    </div>
  </div>
</template>
